name = "baddalink"
pages_build_output_dir = "dist"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
VITE_HOMEPAGE = "https://baddalink.pages.dev"
RTC_CONFIG = "ewogICJpY2VTZXJ2ZXJzIjogWwogICAgewogICAgICAidXJscyI6IFsic3R1bjpzdHVuLmNsb3VkZmxhcmUuY29tOjM0NzgiXQogICAgfSwKICAgIHsKICAgICAgInVybHMiOiBbInN0dW46c3R1bi5sLmdvb2dsZS5jb206MTkzMDIiXQogICAgfSwKICAgIHsKICAgICAgInVybHMiOiBbInN0dW46c3R1bjEubC5nb29nbGUuY29tOjE5MzAyIl0KICAgIH0sCiAgICB7CiAgICAgICJ1cmxzIjogWyJzdHVuOnN0dW4yLmwuZ29vZ2xlLmNvbToxOTMwMiJdCiAgICB9LAogICAgewogICAgICAidXJscyI6IFsic3R1bjpzdHVuLnNlcnZpY2VzLm1vemlsbGEuY29tIl0KICAgIH0sCiAgICB7CiAgICAgICJ1cmxzIjogWyJzdHVuOmJuLXR1cm4yLnhpcnN5cy5jb20iXQogICAgfSwKICAgIHsKICAgICAgInVzZXJuYW1lIjogIm5aOXE2R1VEUlhsSWZ6X0wyQ2hONGduN1lMaktzWWptR3RkWmpVSEU0TEQ3X0prS1QxdDc5dkY4MUlCcUFwTEFBQUFBQUdqX3lucDNZWE5wWm1aaGFYTmhiREl3TURJPSIsCiAgICAgICJjcmVkZW50aWFsIjogImFkMDQ0ZGM2LWIzNmMtMTFmMC1iMzAyLTAyNDJhYzE0MDAwNCIsCiAgICAgICJ1cmxzIjogWwogICAgICAgICJ0dXJuOmJuLXR1cm4yLnhpcnN5cy5jb206ODA/dHJhbnNwb3J0PXVkcCIsCiAgICAgICAgInR1cm46Ym4tdHVybjIueGlyc3lzLmNvbTozNDc4P3RyYW5zcG9ydD11ZHAiLAogICAgICAgICJ0dXJuOmJuLXR1cm4yLnhpcnN5cy5jb206ODA/dHJhbnNwb3J0PXRjcCIsCiAgICAgICAgInR1cm46Ym4tdHVybjIueGlyc3lzLmNvbTozNDc4P3RyYW5zcG9ydD10Y3AiLAogICAgICAgICJ0dXJuczpibi10dXJuMi54aXJzeXMuY29tOjQ0Mz90cmFuc3BvcnQ9dGNwIiwKICAgICAgICAidHVybnM6Ym4tdHVybjIueGlyc3lzLmNvbTo1MzQ5P3RyYW5zcG9ydD10Y3AiCiAgICAgIF0KICAgIH0KICBdCn0="

# Optional: Add custom domain
# routes = [
#   { pattern = "baddalink.your-domain.com/*", zone_name = "your-domain.com" }
# ]